// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";
export const EXPIRE_USER_TOKEN = "EXPIRE_USER_TOKEN";
export const UPDATE_USER_TOKEN = "UPDATE_USER_TOKEN";
export const TOGGLE_ROUTE_PROTECTION = "TOGGLE_ROUTE_PROTECTION";
