// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";
export const EXPIRE_REFRESH_TOKEN = "EXPIRE_USER_TOKEN";
export const UPDATE_ACCESS_TOKEN = "UPDATE_USER_TOKEN";
