// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";
export const EXPIRE_REFRESH_TOKEN = "EXPIRE_USER_TOKEN";
export const UPDATE_ACCESS_TOKEN = "UPDATE_USER_TOKEN";

// Data actions
export const FETCH_USER_PROFILE_DATA = "FETCH_USER_PROFILE_DATA";
export const TOGGLE_FETCHING = "TOGGLE_FETCHING";
export const FETCH_ALL_OPEN_JOBS = "FETCH_ALL_OPEN_JOBS";
export const FETCH_JOB_DETAILS = "FETCH_JOB_DETAILS";
export const FETCH_CLIENT_ALL_JOBS = "FETCH_CLIENT_ALL_JOBS";
